# Generated by Django 5.2.14 on 2026-05-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RNANode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rna_type",
                    models.CharField(
                        choices=[
                            ("miRNA", "miRNA"),
                            ("mRNA", "mRNA"),
                            ("lncRNA", "lncRNA"),
                            ("circRNA", "circRNA"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("species", models.CharField(default="Homo sapiens", max_length=100)),
            ],
            options={
                "db_table": "rna_node",
                "indexes": [
                    models.Index(fields=["name"], name="rna_node_name_2552e1_idx"),
                    models.Index(
                        fields=["rna_type"], name="rna_node_rna_typ_3301e4_idx"
                    ),
                    models.Index(
                        fields=["species"], name="rna_node_species_baf1b6_idx"
                    ),
                    models.Index(
                        fields=["name", "species"], name="rna_node_name_245179_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "rna_type", "species"), name="unique_rna_node"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RNAInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(default="Homo sapiens", max_length=100)),
                ("database", models.CharField(max_length=100)),
                ("interaction_type", models.CharField(max_length=50)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_interactions",
                        to="database.rnanode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_interactions",
                        to="database.rnanode",
                    ),
                ),
            ],
            options={
                "db_table": "rna_interaction",
                "indexes": [
                    models.Index(
                        fields=["source"], name="rna_interac_source__c15e3c_idx"
                    ),
                    models.Index(
                        fields=["target"], name="rna_interac_target__17a1b4_idx"
                    ),
                    models.Index(
                        fields=["species"], name="rna_interac_species_dec7a8_idx"
                    ),
                    models.Index(
                        fields=["database"], name="rna_interac_databas_c23579_idx"
                    ),
                    models.Index(
                        fields=["interaction_type"],
                        name="rna_interac_interac_759d92_idx",
                    ),
                    models.Index(
                        fields=["source", "target"],
                        name="rna_interac_source__5a0cf5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target", "database", "interaction_type"),
                        name="unique_rna_interaction",
                    )
                ],
            },
        ),
    ]
