# Generated by Django 5.2.14 on 2026-05-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                ("field_label", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "filter_field",
                "indexes": [
                    models.Index(
                        fields=["table_name"], name="filter_fiel_table_n_689cdb_idx"
                    ),
                    models.Index(
                        fields=["table_name", "is_active"],
                        name="filter_fiel_table_n_4d9585_idx",
                    ),
                    models.Index(
                        fields=["table_name", "field_name"],
                        name="filter_fiel_table_n_e5a04d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("table_name", "field_name"), name="unique_filter_field"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FilterOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="database.filterfield",
                    ),
                ),
            ],
            options={
                "db_table": "filter_option",
                "indexes": [
                    models.Index(
                        fields=["field"], name="filter_opti_field_i_29a139_idx"
                    ),
                    models.Index(
                        fields=["field", "is_active"],
                        name="filter_opti_field_i_53e174_idx",
                    ),
                    models.Index(
                        fields=["field", "sort_order"],
                        name="filter_opti_field_i_61ee9d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field", "value"), name="unique_filter_option"
                    )
                ],
            },
        ),
    ]
