# Generated by Django 5.2.14 on 2026-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_filterfield_filteroption"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "interaction_database",
            },
        ),
        migrations.RemoveConstraint(
            model_name="rnainteraction",
            name="unique_rna_interaction",
        ),
        migrations.RemoveIndex(
            model_name="rnainteraction",
            name="rna_interac_databas_c23579_idx",
        ),
        migrations.RemoveField(
            model_name="rnainteraction",
            name="database",
        ),
        migrations.AddIndex(
            model_name="interactiondatabase",
            index=models.Index(fields=["name"], name="interaction_name_485df4_idx"),
        ),
        migrations.AddField(
            model_name="rnainteraction",
            name="databases",
            field=models.ManyToManyField(
                blank=True,
                related_name="interactions",
                to="database.interactiondatabase",
            ),
        ),
        migrations.AddConstraint(
            model_name="rnainteraction",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "species", "interaction_type"),
                name="unique_rna_interaction",
            ),
        ),
    ]
