# Generated by Django 5.2.14 on 2026-06-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_interactiondatabase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(max_length=100, unique=True)),
                ("programme", models.CharField(max_length=50)),
                ("obs_type", models.CharField(max_length=50)),
                ("reference", models.CharField(max_length=50)),
                ("cancer_type", models.CharField(max_length=50)),
                ("cancer_type_full_name", models.CharField(max_length=255)),
                (
                    "gene_bio_type",
                    models.CharField(
                        choices=[
                            ("miRNA", "miRNA"),
                            ("mRNA", "mRNA"),
                            ("lncRNA", "lncRNA"),
                            ("circRNA", "circRNA"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("workflow", models.CharField(blank=True, default="", max_length=100)),
                ("sample_nums", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "dataset_metadata",
                "indexes": [
                    models.Index(
                        fields=["programme"], name="dataset_met_program_2c1f25_idx"
                    ),
                    models.Index(
                        fields=["cancer_type"], name="dataset_met_cancer__86039e_idx"
                    ),
                    models.Index(
                        fields=["gene_bio_type"], name="dataset_met_gene_bi_905692_idx"
                    ),
                    models.Index(
                        fields=["reference"], name="dataset_met_referen_7de86e_idx"
                    ),
                    models.Index(
                        fields=["programme", "cancer_type"],
                        name="dataset_met_program_e751a4_idx",
                    ),
                    models.Index(
                        fields=["cancer_type", "gene_bio_type"],
                        name="dataset_met_cancer__0aa238_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "programme",
                            "cancer_type",
                            "gene_bio_type",
                            "reference",
                        ),
                        name="unique_dataset_metadata_record",
                    )
                ],
            },
        ),
    ]
