# Generated by Django 5.2.14 on 2026-06-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_remove_datasetmetadata_unique_dataset_metadata_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmetadata",
            name="cell_nums",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="datasetmetadata",
            name="cancer_type_full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="datasetmetadata",
            name="obs_type",
            field=models.CharField(
                choices=[("sample", "sample"), ("cell", "cell")],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="datasetmetadata",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddIndex(
            model_name="datasetmetadata",
            index=models.Index(
                fields=["obs_type"], name="dataset_met_obs_typ_3f06f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetmetadata",
            index=models.Index(
                fields=["programme", "obs_type"], name="dataset_met_program_45546a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetmetadata",
            index=models.Index(
                fields=["programme", "obs_type", "gene_bio_type"],
                name="dataset_met_program_5d809f_idx",
            ),
        ),
    ]
