# Generated by Django 5.2.14 on 2026-06-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_datasetmetadata_cell_nums_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmetadata",
            name="spot_nums",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="datasetmetadata",
            name="obs_type",
            field=models.CharField(
                choices=[("sample", "sample"), ("cell", "cell"), ("spot", "spot")],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="datasetmetadata",
            index=models.Index(
                fields=["obs_type", "gene_bio_type"],
                name="dataset_met_obs_typ_565bc1_idx",
            ),
        ),
    ]
