# Generated by Django 5.2.14 on 2026-07-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_datasetmetadata_spot_nums_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetAxisFinalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("TCGA", "TCGA"), ("TIMEDB", "TIMEDB")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[("module2", "Module 2"), ("module3", "Module 3")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("dataset_name", models.CharField(db_index=True, max_length=128)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("common", "Common"),
                            ("grade", "Grade"),
                            ("stage", "Stage"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "group_by",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "annotation_dir_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "annotation_file_prefix",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "axis_final_file_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("axis_final_file_path", models.TextField(blank=True, default="")),
                (
                    "file_sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dataset_axis_final_project",
                "indexes": [
                    models.Index(
                        fields=["source", "module", "dataset_name"],
                        name="idx_dataset_axis_project_base",
                    ),
                    models.Index(
                        fields=["dataset_name", "group_type"],
                        name="idx_dataset_axis_project_group",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source",
                            "module",
                            "dataset_name",
                            "group_type",
                            "group_by",
                        ),
                        name="uniq_dataset_axis_project",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DatasetAxisFinalOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.PositiveIntegerField()),
                (
                    "axis_signature",
                    models.CharField(
                        db_index=True,
                        help_text="axis_type|miRNA|mRNA|lncRNA|circRNA",
                        max_length=1024,
                    ),
                ),
                ("axis_id", models.CharField(db_index=True, max_length=512)),
                (
                    "axis_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "axis_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "miRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "mRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "lncRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "circRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("mRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "mRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("miRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "miRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("lncRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "lncRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("circRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "circRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_occurrences",
                        to="database.datasetaxisfinalproject",
                    ),
                ),
            ],
            options={
                "db_table": "dataset_axis_final_occurrence",
            },
        ),
        migrations.CreateModel(
            name="AxisSignatureProjectIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("axis_signature", models.CharField(db_index=True, max_length=1024)),
                ("source", models.CharField(db_index=True, max_length=20)),
                ("module", models.CharField(db_index=True, max_length=20)),
                ("dataset_name", models.CharField(db_index=True, max_length=128)),
                ("group_type", models.CharField(db_index=True, max_length=20)),
                (
                    "group_by",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("axis_id", models.CharField(blank=True, default="", max_length=512)),
                ("axis_type", models.CharField(blank=True, default="", max_length=128)),
                (
                    "axis_regulation",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signature_index_rows",
                        to="database.datasetaxisfinaloccurrence",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_signature_indexes",
                        to="database.datasetaxisfinalproject",
                    ),
                ),
            ],
            options={
                "db_table": "axis_signature_project_index",
            },
        ),
        migrations.AddIndex(
            model_name="datasetaxisfinaloccurrence",
            index=models.Index(
                fields=["axis_signature"], name="idx_axis_occ_signature"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetaxisfinaloccurrence",
            index=models.Index(
                fields=["project", "axis_signature"], name="idx_axis_occ_project_sig"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetaxisfinaloccurrence",
            index=models.Index(
                fields=["miRNA", "mRNA"], name="idx_axis_occ_mirna_mrna"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetaxisfinaloccurrence",
            index=models.Index(
                fields=["miRNA", "mRNA", "lncRNA"], name="idx_axis_occ_lncrna"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetaxisfinaloccurrence",
            index=models.Index(
                fields=["miRNA", "mRNA", "circRNA"], name="idx_axis_occ_circrna"
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetaxisfinaloccurrence",
            constraint=models.UniqueConstraint(
                fields=("project", "axis_signature"), name="uniq_project_axis_signature"
            ),
        ),
        migrations.AddIndex(
            model_name="axissignatureprojectindex",
            index=models.Index(
                fields=["axis_signature"], name="idx_axis_sig_project_sig"
            ),
        ),
        migrations.AddIndex(
            model_name="axissignatureprojectindex",
            index=models.Index(
                fields=["axis_signature", "source"], name="idx_axis_sig_project_source"
            ),
        ),
        migrations.AddIndex(
            model_name="axissignatureprojectindex",
            index=models.Index(
                fields=["axis_signature", "dataset_name"],
                name="idx_axis_sig_project_dataset",
            ),
        ),
        migrations.AddIndex(
            model_name="axissignatureprojectindex",
            index=models.Index(
                fields=["axis_signature", "group_type"],
                name="idx_axis_sig_project_group",
            ),
        ),
        migrations.AddIndex(
            model_name="axissignatureprojectindex",
            index=models.Index(
                fields=["dataset_name", "group_type"], name="idx_axis_sig_dataset_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="axissignatureprojectindex",
            constraint=models.UniqueConstraint(
                fields=("axis_signature", "project"),
                name="uniq_axis_signature_project_index",
            ),
        ),
    ]
