# Generated by Django 5.2.14 on 2026-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "database",
            "0008_datasetaxisfinalproject_datasetaxisfinaloccurrence_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AxisRecurrentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "axis_signature",
                    models.CharField(db_index=True, max_length=1024, unique=True),
                ),
                (
                    "axis_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "miRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "mRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "lncRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "circRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "project_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "dataset_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "tcga_project_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "timedb_project_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "regulation_pattern_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of distinct non-empty axis_regulation patterns.",
                    ),
                ),
                (
                    "dominant_axis_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("dominant_regulation_count", models.PositiveIntegerField(default=0)),
                (
                    "regulation_consistent",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when all non-empty occurrences have the same axis_regulation pattern.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "axis_recurrent_summary",
                "indexes": [
                    models.Index(
                        fields=["-project_count", "axis_signature"],
                        name="idx_axis_recur_project_count",
                    ),
                    models.Index(
                        fields=["-dataset_count", "axis_signature"],
                        name="idx_axis_recur_dataset_count",
                    ),
                    models.Index(
                        fields=["axis_type", "-project_count"],
                        name="idx_axis_recur_type_count",
                    ),
                    models.Index(
                        fields=["regulation_consistent", "-project_count"],
                        name="idx_axis_recur_reg_count",
                    ),
                    models.Index(
                        fields=["miRNA", "mRNA"], name="idx_axis_recur_mirna_mrna"
                    ),
                ],
            },
        ),
    ]
