# Generated by Django 5.2.14 on 2026-08-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0009_axisrecurrentsummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxisObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.PositiveIntegerField()),
                (
                    "source_axis_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1024
                    ),
                ),
                (
                    "source_axis_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "axis_observation",
            },
        ),
        migrations.CreateModel(
            name="CanonicalAxis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature_version", models.PositiveSmallIntegerField(default=2)),
                (
                    "axis_key",
                    models.CharField(
                        help_text="SHA-256 of the normalized structural signature: miRNA|mRNA|lncRNA|circRNA.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "axis_signature",
                    models.TextField(help_text="miRNA|mRNA|lncRNA|circRNA"),
                ),
                (
                    "axis_type",
                    models.CharField(
                        choices=[
                            ("mRNA-miRNA", "mRNA-miRNA"),
                            ("mRNA-miRNA-lncRNA", "mRNA-miRNA-lncRNA"),
                            ("mRNA-miRNA-circRNA", "mRNA-miRNA-circRNA"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("miRNA", models.CharField(db_index=True, max_length=255)),
                ("mRNA", models.CharField(db_index=True, max_length=255)),
                (
                    "lncRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "circRNA",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "canonical_axis",
            },
        ),
        migrations.CreateModel(
            name="AxisResultArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_kind",
                    models.CharField(
                        choices=[("axis_final", "Axis Final"), ("sponge", "Sponge")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.TextField()),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "schema_version",
                    models.CharField(blank=True, default="v1", max_length=32),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "axis_result_artifact",
            },
        ),
        migrations.CreateModel(
            name="AxisDatasetContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_source",
                    models.CharField(
                        choices=[("TCGA", "TCGA"), ("TIMEDB", "TIMEDB")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[("module2", "Module 2"), ("module3", "Module 3")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("other", "Other"),
                            ("grade", "Grade"),
                            ("stage", "Stage"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "group_by",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "annotation_dir_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "annotation_file_prefix",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_metadata",
                    models.ForeignKey(
                        db_column="dataset_name",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="axis_dataset_contexts",
                        to="database.datasetmetadata",
                        to_field="dataset",
                    ),
                ),
            ],
            options={
                "db_table": "axis_dataset_context",
            },
        ),
        migrations.CreateModel(
            name="AxisContextPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_count", models.PositiveIntegerField(default=0)),
                (
                    "axis_final_observation_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("sponge_observation_count", models.PositiveIntegerField(default=0)),
                ("has_axis_final", models.BooleanField(db_index=True, default=False)),
                ("has_sponge", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_presences",
                        to="database.axisdatasetcontext",
                    ),
                ),
            ],
            options={
                "db_table": "axis_context_presence",
            },
        ),
        migrations.CreateModel(
            name="AxisFinalEvidence",
            fields=[
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="axis_final_evidence",
                        serialize=False,
                        to="database.axisobservation",
                    ),
                ),
                (
                    "axis_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("mRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "mRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("miRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "miRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("lncRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "lncRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("circRNA_log2FC", models.FloatField(blank=True, null=True)),
                (
                    "circRNA_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
            ],
            options={
                "db_table": "axis_final_evidence",
            },
        ),
        migrations.CreateModel(
            name="SpongeEvidence",
            fields=[
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sponge_evidence",
                        serialize=False,
                        to="database.axisobservation",
                    ),
                ),
                ("cor", models.FloatField(blank=True, null=True)),
                ("pcor", models.FloatField(blank=True, null=True)),
                ("mscor", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "sponge_evidence",
            },
        ),
        migrations.CreateModel(
            name="AxisFinalRecurrentSummary",
            fields=[
                (
                    "axis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="axis_final_recurrent_summary",
                        serialize=False,
                        to="database.canonicalaxis",
                    ),
                ),
                (
                    "context_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("observation_count", models.PositiveIntegerField(default=0)),
                ("regulation_pattern_count", models.PositiveIntegerField(default=0)),
                (
                    "dominant_axis_regulation",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("dominant_regulation_count", models.PositiveIntegerField(default=0)),
                (
                    "regulation_consistent",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "axis_final_recur_summary",
            },
        ),
        migrations.CreateModel(
            name="AxisStructureRecurrentSummary",
            fields=[
                (
                    "axis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recurrent_summary",
                        serialize=False,
                        to="database.canonicalaxis",
                    ),
                ),
                (
                    "context_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "dataset_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "tcga_dataset_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "timedb_dataset_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("tcga_context_count", models.PositiveIntegerField(default=0)),
                ("timedb_context_count", models.PositiveIntegerField(default=0)),
                ("module2_context_count", models.PositiveIntegerField(default=0)),
                ("module3_context_count", models.PositiveIntegerField(default=0)),
                (
                    "axis_final_context_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "sponge_context_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("both_result_context_count", models.PositiveIntegerField(default=0)),
                ("summary_version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "axis_structure_recur_summary",
            },
        ),
        migrations.AddIndex(
            model_name="canonicalaxis",
            index=models.Index(
                fields=["miRNA", "mRNA"], name="idx_canon_axis_mir_mrna"
            ),
        ),
        migrations.AddIndex(
            model_name="canonicalaxis",
            index=models.Index(
                fields=["miRNA", "mRNA", "lncRNA"], name="idx_canon_axis_lncrna"
            ),
        ),
        migrations.AddIndex(
            model_name="canonicalaxis",
            index=models.Index(
                fields=["miRNA", "mRNA", "circRNA"], name="idx_canon_axis_circrna"
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalaxis",
            constraint=models.CheckConstraint(
                condition=models.Q(("miRNA__gt", ""), ("mRNA__gt", "")),
                name="axis_need_mirna_mrna",
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalaxis",
            constraint=models.CheckConstraint(
                condition=models.Q(("lncRNA", ""), ("circRNA", ""), _connector="OR"),
                name="axis_one_cerna_kind",
            ),
        ),
        migrations.AddField(
            model_name="axisobservation",
            name="axis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="database.canonicalaxis",
            ),
        ),
        migrations.AddField(
            model_name="axiscontextpresence",
            name="axis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context_presences",
                to="database.canonicalaxis",
            ),
        ),
        migrations.AddField(
            model_name="axisresultartifact",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_artifacts",
                to="database.axisdatasetcontext",
            ),
        ),
        migrations.AddField(
            model_name="axisobservation",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="database.axisresultartifact",
            ),
        ),
        migrations.AddIndex(
            model_name="axisdatasetcontext",
            index=models.Index(
                fields=["dataset_source", "module", "dataset_metadata"],
                name="idx_axis_ctx_source_mod",
            ),
        ),
        migrations.AddIndex(
            model_name="axisdatasetcontext",
            index=models.Index(
                fields=["dataset_metadata", "group_type"],
                name="idx_axis_ctx_dataset_grp",
            ),
        ),
        migrations.AddConstraint(
            model_name="axisdatasetcontext",
            constraint=models.UniqueConstraint(
                fields=(
                    "dataset_source",
                    "module",
                    "dataset_metadata",
                    "group_type",
                    "group_by",
                ),
                name="uniq_axis_dataset_context",
            ),
        ),
        migrations.AddIndex(
            model_name="spongeevidence",
            index=models.Index(fields=["cor"], name="idx_sponge_cor"),
        ),
        migrations.AddIndex(
            model_name="spongeevidence",
            index=models.Index(fields=["pcor"], name="idx_sponge_pcor"),
        ),
        migrations.AddIndex(
            model_name="spongeevidence",
            index=models.Index(fields=["mscor"], name="idx_sponge_mscor"),
        ),
        migrations.AddIndex(
            model_name="axisfinalrecurrentsummary",
            index=models.Index(
                fields=["regulation_consistent", "-context_count"],
                name="idx_axis_final_recur_reg",
            ),
        ),
        migrations.AddIndex(
            model_name="axisstructurerecurrentsummary",
            index=models.Index(
                fields=["-context_count", "axis"], name="idx_axis_recur_ctx_count"
            ),
        ),
        migrations.AddIndex(
            model_name="axisstructurerecurrentsummary",
            index=models.Index(
                fields=["-dataset_count", "axis"], name="idx_axis_recur_ds_count"
            ),
        ),
        migrations.AddIndex(
            model_name="axiscontextpresence",
            index=models.Index(
                fields=["axis", "context"], name="idx_axis_presence_axis_ctx"
            ),
        ),
        migrations.AddIndex(
            model_name="axiscontextpresence",
            index=models.Index(
                fields=["axis", "has_axis_final"], name="idx_axis_presence_final"
            ),
        ),
        migrations.AddIndex(
            model_name="axiscontextpresence",
            index=models.Index(
                fields=["axis", "has_sponge"], name="idx_axis_presence_sponge"
            ),
        ),
        migrations.AddConstraint(
            model_name="axiscontextpresence",
            constraint=models.UniqueConstraint(
                fields=("context", "axis"), name="uniq_axis_context_presence"
            ),
        ),
        migrations.AddIndex(
            model_name="axisresultartifact",
            index=models.Index(
                fields=["context", "result_kind", "is_active"],
                name="idx_axis_art_ctx_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="axisresultartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("context", "result_kind"),
                name="uniq_active_axis_artifact",
            ),
        ),
        migrations.AddIndex(
            model_name="axisobservation",
            index=models.Index(
                fields=["axis", "artifact"], name="idx_axis_obs_axis_art"
            ),
        ),
        migrations.AddConstraint(
            model_name="axisobservation",
            constraint=models.UniqueConstraint(
                fields=("artifact", "row_index"), name="uniq_axis_artifact_row"
            ),
        ),
        migrations.AddConstraint(
            model_name="axisobservation",
            constraint=models.UniqueConstraint(
                fields=("artifact", "axis"), name="uniq_axis_artifact_axis"
            ),
        ),
    ]
