# Generated by Django 5.2.14 on 2026-06-12 14:30

import analysis.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomListQueryTask",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=300, null=True)),
                ("task_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Success"),
                            ("P", "Pending"),
                            ("F", "Failed"),
                            ("R", "Running"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                (
                    "map_info",
                    models.CharField(
                        help_text="Selected immune annotation file value, e.g. ImmiRImmiR_ACC.",
                        max_length=200,
                    ),
                ),
                (
                    "rnas",
                    models.JSONField(
                        default=analysis.models.default_rnas,
                        help_text="Input RNA lists grouped by miRNA, mRNA, lncRNA and circRNA.",
                    ),
                ),
            ],
            options={
                "db_table": "custom_list_query_task",
                "ordering": ["-create_time"],
            },
        ),
    ]
