# Generated by Django 5.2.14 on 2026-06-13 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairedCohortTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("user", models.CharField(blank=True, default="", max_length=128)),
                ("task_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Running"),
                            (2, "Success"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("map_info", models.CharField(max_length=255)),
                ("deg_method", models.CharField(max_length=32)),
                ("mrna_file", models.CharField(blank=True, default="", max_length=255)),
                (
                    "mirna_file",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "lncrna_file",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("meta_file", models.CharField(blank=True, default="", max_length=255)),
                ("logfc_cutoff_mrna", models.FloatField(default=1)),
                ("padj_cutoff_mrna", models.FloatField(default=0.05)),
                ("logfc_cutoff_mirna", models.FloatField(default=1)),
                ("padj_cutoff_mirna", models.FloatField(default=0.05)),
                ("logfc_cutoff_lncrna", models.FloatField(default=1)),
                ("padj_cutoff_lncrna", models.FloatField(default=0.05)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "paired_cohort_task",
                "ordering": ["-create_time"],
            },
        ),
    ]
