# Generated by Django 5.2.14 on 2026-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_pairedcohorttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairedcohorttask",
            name="circrna_file",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pairedcohorttask",
            name="logfc_cutoff_circrna",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="pairedcohorttask",
            name="padj_cutoff_circrna",
            field=models.FloatField(default=0.1),
        ),
    ]
