# Generated by Django 5.2.14 on 2026-06-25 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_pairedcohorttask_circrna_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HybridReferenceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("user", models.CharField(blank=True, default="", max_length=128)),
                ("task_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Running"),
                            (2, "Success"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("tcga_type", models.CharField(db_index=True, max_length=64)),
                (
                    "lncrna_type",
                    models.CharField(
                        choices=[
                            ("log2count", "log2count"),
                            ("log2fpkm", "log2fpkm"),
                            ("log2fpkmuq", "log2fpkmuq"),
                            ("log2tpm", "log2tpm"),
                        ],
                        default="log2tpm",
                        max_length=32,
                    ),
                ),
                ("map_info", models.CharField(max_length=255)),
                (
                    "deg_method",
                    models.CharField(
                        choices=[("limma", "limma"), ("deseq2", "deseq2")],
                        default="limma",
                        max_length=32,
                    ),
                ),
                ("mrna_file", models.CharField(blank=True, default="", max_length=255)),
                ("meta_file", models.CharField(blank=True, default="", max_length=255)),
                ("logfc_cutoff_mrna", models.FloatField(default=1.0)),
                ("padj_cutoff_mrna", models.FloatField(default=0.05)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hybrid_reference_task",
                "ordering": ["-create_time"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="hybrid_refe_status_b5de56_idx"
                    ),
                    models.Index(
                        fields=["tcga_type"], name="hybrid_refe_tcga_ty_40fdb6_idx"
                    ),
                    models.Index(
                        fields=["create_time"], name="hybrid_refe_create__da681c_idx"
                    ),
                ],
            },
        ),
    ]
