# Generated by Django 5.2.14 on 2026-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_hybridreferencetask"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairedcohorttask",
            name="cancer_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pairedcohorttask",
            name="use_padj",
            field=models.BooleanField(default=True),
        ),
    ]
