# Generated by Django 5.2.14 on 2026-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_pairedcohorttask_cancer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hybridreferencetask",
            name="cancer_type",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="hybridreferencetask",
            name="use_padj",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="hybridreferencetask",
            index=models.Index(
                fields=["cancer_type"], name="hybrid_refe_cancer__2c8bda_idx"
            ),
        ),
    ]
