# Generated by Django 5.2.14 on 2026-06-27 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0006_hybridreferencetask_cancer_type_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hybridreferencetask",
            name="hybrid_refe_cancer__2c8bda_idx",
        ),
        migrations.RemoveField(
            model_name="hybridreferencetask",
            name="cancer_type",
        ),
    ]
