# Generated by Django 5.2.14 on 2026-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analysis",
            "0007_remove_hybridreferencetask_hybrid_refe_cancer__2c8bda_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customlistquerytask",
            name="cancer_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Cancer type used by run_module1.sh, e.g. ACC.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customlistquerytask",
            name="has_mrna_direction",
            field=models.BooleanField(
                default=False,
                help_text="Whether mRNA input is directional. Currently fixed to False for frontend submission.",
            ),
        ),
        migrations.AlterField(
            model_name="customlistquerytask",
            name="map_info",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Deprecated for CustomListQueryTask. Previously selected immune annotation file value, e.g. ImmiRImmiR_ACC.",
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="customlistquerytask",
            index=models.Index(fields=["status"], name="custom_list_status_76463d_idx"),
        ),
        migrations.AddIndex(
            model_name="customlistquerytask",
            index=models.Index(
                fields=["cancer_type"], name="custom_list_cancer__68bc90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customlistquerytask",
            index=models.Index(
                fields=["create_time"], name="custom_list_create__fb37f3_idx"
            ),
        ),
    ]
