# Generated by Django 5.2.14 on 2026-07-11 12:47

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0008_customlistquerytask_cancer_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customlistquerytask",
            name="has_mrna_direction",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether mRNA input is directional. When true, mRNA_up and mRNA_down are used instead of the standard mRNA list.",
            ),
        ),
        migrations.AlterField(
            model_name="customlistquerytask",
            name="rnas",
            field=models.JSONField(
                default=analysis.models.default_rnas,
                help_text="Input RNA lists grouped by miRNA, mRNA, mRNA_up, mRNA_down, lncRNA and circRNA.",
            ),
        ),
    ]
