# Generated by Django 5.2.14 on 2026-07-23 08:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0009_alter_customlistquerytask_has_mrna_direction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SCSTHybridReferenceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("user", models.CharField(blank=True, default="", max_length=128)),
                ("task_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Running"),
                            (2, "Success"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("sc", "Single-cell RNA-seq"),
                            ("st", "Spatial transcriptomics"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("tcga_type", models.CharField(db_index=True, max_length=64)),
                (
                    "lncrna_type",
                    models.CharField(
                        choices=[
                            ("log2count", "log2count"),
                            ("log2fpkm", "log2fpkm"),
                            ("log2fpkmuq", "log2fpkmuq"),
                            ("log2tpm", "log2tpm"),
                        ],
                        default="log2tpm",
                        max_length=32,
                    ),
                ),
                ("exp_file", models.CharField(blank=True, default="", max_length=255)),
                ("meta_file", models.CharField(blank=True, default="", max_length=255)),
                ("group_col", models.CharField(max_length=128)),
                ("map_info", models.CharField(max_length=255)),
                ("use_padj", models.BooleanField(default=True)),
                ("logfc_cutoff_mrna", models.FloatField(default=1.0)),
                ("padj_cutoff_mrna", models.FloatField(default=0.05)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "scst_hybrid_reference_task",
                "ordering": ["-create_time"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="scst_hybrid_status_a6278e_idx"
                    ),
                    models.Index(
                        fields=["data_type"], name="scst_hybrid_data_ty_b6835d_idx"
                    ),
                    models.Index(
                        fields=["tcga_type"], name="scst_hybrid_tcga_ty_15ae3a_idx"
                    ),
                    models.Index(
                        fields=["create_time"], name="scst_hybrid_create__aa7f47_idx"
                    ),
                ],
            },
        ),
    ]
